inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - sorbet/**/*.rbi

Layout/LineLength:
  Max: 120

Lint/UnusedMethodArgument:
  Exclude:
    - lib/open_feature/multiple_source_provider.rb
    - lib/open_feature/no_op_provider.rb

Metrics/ClassLength:
  Exclude:
    - lib/open_feature/client.rb
    - test/open_feature/client_test.rb
    - test/open_feature/multiple_source_provider_test.rb

Metrics/MethodLength:
  Exclude:
    - test/**/*

Style/AccessorGrouping:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
