on:
  push:
    branches: main

jobs:
  code_quality:
    uses: ./.github/workflows/main.yml
  release-gem:
    runs-on: ubuntu-latest
    needs: code_quality
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{github.head_ref}}
      - name: Setup
        run: |
          git config user.email "maxveldink@gmail.com"
          git config user.name "Max VelDink"
          mkdir -p $HOME/.gem
          printf "%s\n" "rubygems_api_key: ${{secrets.RUBY_GEMS_PUSH_API_KEY}}" > $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
      - name: Install
        run: gem install gemsmith
      - name: Publish
        run: gemsmith --publish

